name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      # - name: Set up Terraform
      #   uses: hashicorp/setup-terraform@v2
      #   with:
      #     terraform_version: '1.6.0'

      # - name: Terraform Init
      #   working-directory: terraform
      #   run: terraform init

      # - name: Terraform Plan
      #   working-directory: terraform
      #   run: terraform plan

      # - name: Terraform Apply
      #   if: github.ref == 'refs/heads/main'
      #   working-directory: terraform
      #   run: terraform apply -auto-approve
